services:
  django:
    container_name: dteam-django-api
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    env_file:
      - .env
    volumes:
      - .:/opt/pysetup/app
      - .env:/opt/pysetup/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: dteam-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: dteam-redis
    ports:
      - "6379:6379"

  celery:
    container_name: dteam-celery
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    entrypoint: ["./celery-entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - .:/opt/pysetup/app
    depends_on:
      - redis
      - postgres
      - django

  mailhog:
    image: mailhog/mailhog
    container_name: dteam-mailhog
    ports:
      - "8025:8025"

volumes:
  postgres_data:
